name: ci

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Docker build push"
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: andyhuynh/boba-tracker-server
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildArgs: SESSION_SECRET=${{ secrets.SESSION_SECRET }},CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
          tag: latest
      - name: Update API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull andyhuynh/boba-tracker-server:latest
            docker tag andyhuynh/boba-tracker-server:latest dokku/api:latest
            dokku tags:deploy api
